# Generated by Django 2.2.7 on 2019-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Dummy Model',
            },
        ),
    ]
