# Generated by Django 2.2.7 on 2019-12-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0003_auto_20191201_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CLINICS'),
        ),
    ]
