# Generated by Django 2.2.7 on 2019-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0004_appointments_clinic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinics',
            options={'verbose_name_plural': 'clinics'},
        ),
        migrations.AlterField(
            model_name='clinics',
            name='clinicName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='emailID',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
