# Generated by Django 2.2.7 on 2019-12-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0005_auto_20191205_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
        migrations.AddField(
            model_name='staff',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CLINICS'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dateOfHire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emailID',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
