# Generated by Django 2.2.7 on 2019-12-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0007_auto_20191205_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_inventory',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CLINICS'),
        ),
        migrations.AlterField(
            model_name='medicine_inventory',
            name='medicationName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine_inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine_inventory',
            name='strength',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
