# Generated by Django 2.2.7 on 2019-12-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0008_auto_20191205_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name_plural': 'administrators'},
        ),
        migrations.AlterModelOptions(
            name='machines',
            options={'verbose_name_plural': 'machines'},
        ),
        migrations.AlterModelOptions(
            name='medicine_inventory',
            options={'verbose_name_plural': 'Medicine Inventory'},
        ),
        
        migrations.AddField(
            model_name='machines',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CLINICS'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='chair',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='dialysateFlow',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dialysisType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CONSULTATIONS',
            fields=[
                ('consultationID', models.IntegerField(primary_key=True, serialize=False)),
                ('consultDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('createts', models.DateTimeField(auto_now_add=True)),
                ('modifyts', models.DateTimeField(auto_now=True)),
                ('appoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.APPOINTMENTS')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.PATIENTS')),
            ],
        ),
    ]
