# Generated by Django 2.2.7 on 2019-12-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0009_auto_20191205_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'appointments'},
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='inclinics',
            name='staff',
        ),
        migrations.DeleteModel(
            name='ADMINS',
        ),
    ]
