# Generated by Django 2.2.7 on 2019-12-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0011_auto_20191205_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'appointments'},
        ),
        migrations.AlterModelOptions(
            name='consultations',
            options={'verbose_name_plural': 'consultations'},
        ),
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'doctors'},
        ),
        migrations.AddField(
            model_name='doctors',
            name='consult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CONSULTATIONS'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctorType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='onCall',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
