# Generated by Django 2.2.7 on 2019-12-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0012_auto_20191205_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptions',
            options={'verbose_name_plural': 'prescriptions'},
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='bfr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='bufferSetting',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dfr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dialysateTemp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='doseOrdered',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='edw',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='heparinBolus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='instruction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='lastGivenDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='lastGivenDose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='sodiumSetting',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='treatmentTime',
            field=models.DateTimeField(null=True),
        ),
    ]
