# Generated by Django 2.2.7 on 2019-12-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0013_auto_20191205_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpers',
            options={'verbose_name_plural': 'helpers'},
        ),
        migrations.AlterModelOptions(
            name='machine_verifications',
            options={'verbose_name_plural': 'Machine Verification Information'},
        ),
        migrations.AlterModelOptions(
            name='treatments',
            options={'verbose_name_plural': 'Treatment Sessions'},
        ),
        migrations.RenameField(
            model_name='treatments',
            old_name='dialyzedBy',
            new_name='treatmentStartby',
        ),
        migrations.AddField(
            model_name='treatments',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='helperType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machine_verifications',
            name='dialysisFluidTemperature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='arterialAccess',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='arterialPressure',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='dialysisEndWeight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='dialyzate1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='heparinUnitsActual',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='orderedBloodflow',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='targetBloodprocessed',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='totalFluidRemoval',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='treatmentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='treatmentStarttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='ufr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='venousAccess',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='venousPressure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='machine_verifications',
            unique_together=set(),
        ),
    ]
