# Generated by Django 2.2.7 on 2019-12-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0014_auto_20191205_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pre_post',
            options={'verbose_name_plural': 'HD Run Pre/Post Events '},
        ),
        migrations.AlterModelOptions(
            name='run_events',
            options={'verbose_name_plural': 'HD Run Events'},
        ),
        migrations.AlterModelOptions(
            name='run_vitals',
            options={'verbose_name_plural': 'HD Run Vitals'},
        ),
        migrations.AlterModelOptions(
            name='runs',
            options={'verbose_name_plural': 'HD Run Medication'},
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='bpSitting',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='bpStanding',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='catheterInstillation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='dateTimeOfVitals',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='dialyzerAppearance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='noOfDressings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='orderedSaline',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='pulseRate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='respirationRate',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='targetWeight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='vitalComments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='vitalFlag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_post',
            name='weightChange',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='event',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='runEventID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='severity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='run_events',
            name='treatmentname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='bfr',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='bpSitting',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='bpStanding',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='dfr',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='pulse',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='runVitalID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='run_vitals',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='doseGiven',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='medicationName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='runID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runs',
            name='strength',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pre_post',
            unique_together={('treatment', 'vitalFlag')},
        ),
        migrations.AlterUniqueTogether(
            name='run_events',
            unique_together={('treatment', 'runEventID')},
        ),
        migrations.AlterUniqueTogether(
            name='run_vitals',
            unique_together={('treatment', 'runVitalID')},
        ),
        migrations.AlterUniqueTogether(
            name='runs',
            unique_together={('treatment', 'runID')},
        ),
    ]
