# Generated by Django 2.2.7 on 2019-12-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0016_auto_20191205_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialyzer_models',
            options={'verbose_name_plural': 'Dialyzer Models'},
        ),
        migrations.AlterModelOptions(
            name='dialyzer_units',
            options={'verbose_name_plural': 'Dialyzer Units'},
        ),
        migrations.AlterModelOptions(
            name='inclinics',
            options={'verbose_name_plural': 'In-Clinic Treatments'},
        ),
        migrations.AlterModelOptions(
            name='medical_devices',
            options={'verbose_name_plural': 'Medical Devices'},
        ),
        migrations.AlterModelOptions(
            name='outclinics',
            options={'verbose_name_plural': 'Out-Clinic Treatments'},
        ),
        migrations.AlterModelOptions(
            name='prescribed_dosages',
            options={'verbose_name_plural': 'Prescribed Dosages'},
        ),
        migrations.AlterField(
            model_name='dialyzer_models',
            name='dialyzerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dialyzer_units',
            name='dialyzerReuseNumber',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dialyzer_units',
            name='dialyzerTest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inclinics',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.CLINICS'),
        ),
        migrations.AlterField(
            model_name='medical_devices',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medical_devices',
            name='medicalDeviceType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medical_devices',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescribed_dosages',
            name='dosageNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prescribed_dosages',
            name='dosageOrdered',
            field=models.IntegerField(null=True),
        ),
    ]
