# Generated by Django 2.2.7 on 2019-12-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0017_auto_20191205_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainings',
            options={'verbose_name_plural': 'Trainings'},
        ),
    ]
