# Generated by Django 2.2.7 on 2019-12-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0019_auto_20191205_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='consult',
        ),
        migrations.AddField(
            model_name='consultations',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.DOCTORS'),
        ),
        migrations.AlterField(
            model_name='treatments',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
