# Generated by Django 2.2.7 on 2019-12-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0022_auto_20191205_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_verifications',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hd.TECHNICIANS'),
        ),
    ]
