# Generated by Django 2.2.7 on 2019-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0025_auto_20191205_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentsToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointID', models.IntegerField()),
            ],
            options={
                'db_table': 'appoint_today',
                'managed': False,
            },
        ),
    ]
