# Generated by Django 2.2.7 on 2019-12-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0026_appointmentstoday'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentstoday',
            table='appoint_todaygg',
        ),
    ]
