# Generated by Django 2.2.7 on 2019-12-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hd', '0027_auto_20191207_0124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointmentstoday',
            table='appoint_today',
        ),
    ]
